/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XpokornyProjectWlList {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLXpokornyProjectWlListElement extends Components.XpokornyProjectWlList, HTMLStencilElement {
    }
    var HTMLXpokornyProjectWlListElement: {
        prototype: HTMLXpokornyProjectWlListElement;
        new (): HTMLXpokornyProjectWlListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "xpokorny-project-wl-list": HTMLXpokornyProjectWlListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XpokornyProjectWlList {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "xpokorny-project-wl-list": XpokornyProjectWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "xpokorny-project-wl-list": LocalJSX.XpokornyProjectWlList & JSXBase.HTMLAttributes<HTMLXpokornyProjectWlListElement>;
        }
    }
}
