/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XpokornyAmbulanceWlApp {
        "basePath": string;
    }
    interface XpokornyAmbulanceWlEditor {
    }
    interface XpokornyProjectWlList {
    }
}
export interface XpokornyProjectWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXpokornyProjectWlListElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLXpokornyAmbulanceWlAppElement extends Components.XpokornyAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLXpokornyAmbulanceWlAppElement: {
        prototype: HTMLXpokornyAmbulanceWlAppElement;
        new (): HTMLXpokornyAmbulanceWlAppElement;
    };
    interface HTMLXpokornyAmbulanceWlEditorElement extends Components.XpokornyAmbulanceWlEditor, HTMLStencilElement {
    }
    var HTMLXpokornyAmbulanceWlEditorElement: {
        prototype: HTMLXpokornyAmbulanceWlEditorElement;
        new (): HTMLXpokornyAmbulanceWlEditorElement;
    };
    interface HTMLXpokornyProjectWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLXpokornyProjectWlListElement extends Components.XpokornyProjectWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXpokornyProjectWlListElementEventMap>(type: K, listener: (this: HTMLXpokornyProjectWlListElement, ev: XpokornyProjectWlListCustomEvent<HTMLXpokornyProjectWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXpokornyProjectWlListElementEventMap>(type: K, listener: (this: HTMLXpokornyProjectWlListElement, ev: XpokornyProjectWlListCustomEvent<HTMLXpokornyProjectWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXpokornyProjectWlListElement: {
        prototype: HTMLXpokornyProjectWlListElement;
        new (): HTMLXpokornyProjectWlListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "xpokorny-ambulance-wl-app": HTMLXpokornyAmbulanceWlAppElement;
        "xpokorny-ambulance-wl-editor": HTMLXpokornyAmbulanceWlEditorElement;
        "xpokorny-project-wl-list": HTMLXpokornyProjectWlListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XpokornyAmbulanceWlApp {
        "basePath"?: string;
    }
    interface XpokornyAmbulanceWlEditor {
    }
    interface XpokornyProjectWlList {
        "onEntry-clicked"?: (event: XpokornyProjectWlListCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "xpokorny-ambulance-wl-app": XpokornyAmbulanceWlApp;
        "xpokorny-ambulance-wl-editor": XpokornyAmbulanceWlEditor;
        "xpokorny-project-wl-list": XpokornyProjectWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "xpokorny-ambulance-wl-app": LocalJSX.XpokornyAmbulanceWlApp & JSXBase.HTMLAttributes<HTMLXpokornyAmbulanceWlAppElement>;
            "xpokorny-ambulance-wl-editor": LocalJSX.XpokornyAmbulanceWlEditor & JSXBase.HTMLAttributes<HTMLXpokornyAmbulanceWlEditorElement>;
            "xpokorny-project-wl-list": LocalJSX.XpokornyProjectWlList & JSXBase.HTMLAttributes<HTMLXpokornyProjectWlListElement>;
        }
    }
}
