name: Xpokorny Project uFE CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v1*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci || npm install
    - run: npm run build --if-present
    - run: npm test
